name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: windows-latest
    env:
      # Ensure any optional env vars needed for tests are set here.
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run fast test suite
        run: pytest -m "not integration" --cov=backlog_cli --cov-report=xml --cov-fail-under=90 -q

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml
